# File: ./.forgejo/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # --- JOB 1: LINUX ARTIFACTS (Ubuntu 24.04) ---
  build-linux:
    runs-on: self-hosted-ubuntu
    container:
      image: local/ubuntu-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Linux Binaries
        run: cargo build --release --features gui

      - name: Create Debian Package
        run: |
          cargo deb --no-build --features gui
          mkdir -p dist
          mv target/debian/*.deb dist/

      - name: Create Generic Linux Archives
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            RAW_VERSION="${{ github.ref_name }}"
            CLEAN_VERSION=$(echo "$RAW_VERSION" | sed 's/^v//')
          else
            RAW_VERSION="debug-${{ github.sha }}"
            CLEAN_VERSION="$RAW_VERSION"
          fi
          
          # Source Tarball
          git archive --format=tar.gz --prefix="cfait-${CLEAN_VERSION}/" -o "dist/cfait-source-${RAW_VERSION}.tar.gz" HEAD
          
          # Linux Binary Tarball
          mkdir "cfait-linux-${CLEAN_VERSION}"
          cp target/release/cfait "cfait-linux-${CLEAN_VERSION}/"
          cp target/release/gui "cfait-linux-${CLEAN_VERSION}/cfait-gui"
          cp README.md LICENSE "cfait-linux-${CLEAN_VERSION}/"
          cp assets/cfait.desktop "cfait-linux-${CLEAN_VERSION}/"
          cp assets/cfait.svg "cfait-linux-${CLEAN_VERSION}/"
          tar -czvf "dist/cfait-linux-${RAW_VERSION}.tar.gz" "cfait-linux-${CLEAN_VERSION}"

      # Upload to runner storage (v3 for Forgejo compatibility)
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: dist/*

  # --- JOB 2: ANDROID BUILD (Ubuntu 24.04) ---
  build-android:
    runs-on: self-hosted-ubuntu
    container:
      image: local/ubuntu-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry
        - gradle-cache:/root/.gradle

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Keystore
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.ANDROID_SIGNING_KEYSTORE_B64 }}" | base64 --decode > cfait-release.keystore

      - name: Build Rust JNI Libs
        run: |
          cargo ndk \
            -t aarch64-linux-android \
            -t armv7-linux-androideabi \
            -t x86_64-linux-android \
            -o ./android/app/src/main/jniLibs \
            build --release --lib --features mobile

      - name: Build Signed Android App Bundle
        if: startsWith(github.ref, 'refs/tags/')
        env:
          KEYSTORE_FILE: "${{ github.workspace }}/cfait-release.keystore"
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon

      # 4. Convert AAB to Universal APK using bundletool
      - name: Generate Universal APK from AAB
        if: startsWith(github.ref, 'refs/tags/')
        env:
          KEYSTORE_FILE: "${{ github.workspace }}/cfait-release.keystore"
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          # Download bundletool
          wget -q https://github.com/google/bundletool/releases/download/1.16.0/bundletool-all-1.16.0.jar
          
          # Find the AAB file
          AAB_FILE=$(find android/app/build/outputs/bundle/release -name '*.aab' -print -quit)
          
          # Run bundletool to create an APK set (.apks) containing a universal APK
          java -jar bundletool-all-1.16.0.jar build-apks \
            --bundle="$AAB_FILE" \
            --output=cfait.apks \
            --mode=universal \
            --ks="$KEYSTORE_FILE" \
            --ks-pass=pass:$KEYSTORE_PASSWORD \
            --ks-key-alias=$KEY_ALIAS \
            --key-pass=pass:$KEY_PASSWORD

          # Extract the universal APK from the .apks archive
          unzip cfait.apks -d apks/
          mv apks/universal.apk "cfait-android-${{ github.ref_name }}.apk"

      # 5. Upload Artifacts
      - name: Prepare Artifacts for Upload
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          RAW_VERSION="${{ github.ref_name }}"
          mkdir -p dist-android
          # Move the AAB
          find android/app/build/outputs/bundle/release -name '*.aab' -exec cp {} "dist-android/cfait-android-${RAW_VERSION}.aab" \;
          # Move the new APK
          mv "cfait-android-${RAW_VERSION}.apk" dist-android/

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: android-artifacts
          path: dist-android/*

  # --- JOB 3: WINDOWS BUILD & PUBLISH (Arch) ---
  # This job waits for Linux and Android, then bundles everything and releases.
  build-windows-and-publish:
    needs: [build-linux, build-android]
    runs-on: self-hosted-arch
    container:
      image: local/arch-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Download Linux Artifacts
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-artifacts
          path: dist

      # 2. Download Android Artifacts
      - name: Download Android Artifacts
        uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: android-artifacts
          path: dist

      # 3. Build Windows Binaries (On Arch)
      - name: Build Windows Binaries
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu --features gui

      # 4. Package Windows
      - name: Create Windows Archive
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            RAW_VERSION="${{ github.ref_name }}"
          else
            RAW_VERSION="debug-${{ github.sha }}"
          fi
          
          mkdir -p windows-staging
          cp target/x86_64-pc-windows-gnu/release/cfait.exe windows-staging/
          cp target/x86_64-pc-windows-gnu/release/gui.exe windows-staging/cfait-gui.exe
          cp README.md LICENSE windows-staging/
          
          (cd windows-staging && zip -r "../dist/cfait-windows-$RAW_VERSION.zip" .)

      # 5. Generate Changelog
      - name: Generate Changelog
        run: |
          git-cliff --config cliff.toml --verbose --latest --strip header --output dist/CHANGELOG_RELEASE.md

      # 6. Handle AUR
      - name: Prepare AUR Files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          RAW_VERSION="${{ github.ref_name }}"
          CLEAN_VER=$(echo "$RAW_VERSION" | sed 's/^v//')
          
          cd dist
          
          # Verify Linux source tarball exists
          if [ ! -f "cfait-source-${RAW_VERSION}.tar.gz" ]; then
            echo "Error: Source tarball not found"
            exit 1
          fi
          
          HASH=$(sha256sum "cfait-source-${RAW_VERSION}.tar.gz" | awk '{print $1}')
          
          cp ../packaging/arch/PKGBUILD .
          
          sed -i "s/pkgver=.*/pkgver=${CLEAN_VER}/" PKGBUILD
          sed -i "s/'SKIP'/'$HASH'/" PKGBUILD
          NEW_SOURCE_URL="https://codeberg.org/trougnouf/cfait/releases/download/${RAW_VERSION}/cfait-source-${RAW_VERSION}.tar.gz"
          sed -i "s|source=.*|source=(\"cfait-source-${RAW_VERSION}.tar.gz::${NEW_SOURCE_URL}\")|" PKGBUILD
          
          # Fix ownership so builder user can write .SRCINFO
          chown -R builder:builder .
          su builder -c "makepkg --printsrcinfo > .SRCINFO"

      # 7. Upload Everything (Atomic Release)
      - name: Upload to Codeberg Releases
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          tea login add --name codeberg --url ${{ github.server_url }} --token ${{ secrets.RELEASE_TOKEN }}
          tea release delete --repo ${{ github.repository }} --confirm ${{ github.ref_name }} || true
          
          tea release create \
            --repo "${{ github.repository }}" \
            --title "${{ github.ref_name }}" \
            --tag "${{ github.ref_name }}" \
            --note-file dist/CHANGELOG_RELEASE.md

          echo "Uploading all assets..."
          cd dist
          for file in *; do
            # Upload everything in dist except metadata files
            if [ "$file" != "CHANGELOG_RELEASE.md" ] && [ "$file" != "PKGBUILD" ] && [ "$file" != ".SRCINFO" ] && [ -f "$file" ]; then
              echo "Uploading $file..."
              tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} "$file"
            fi
          done
          
          # Upload PKGBUILD separately
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} PKGBUILD

      # 8. Push to AUR
      - name: Push to AUR
        if: startsWith(github.ref, 'refs/tags/')
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
        run: |
          mkdir -p /root/.ssh
          echo "$AUR_SSH_KEY" > /root/.ssh/aur_key
          chmod 600 /root/.ssh/aur_key
          ssh-keyscan aur.archlinux.org >> /root/.ssh/known_hosts
          export GIT_SSH_COMMAND="ssh -i /root/.ssh/aur_key -o UserKnownHostsFile=/root/.ssh/known_hosts"
          
          git config --global user.name "Cfait Bot (Benoit Brummer)"
          git config --global user.email "trougnouf@gmail.com"
          
          git clone ssh://aur@aur.archlinux.org/cfait.git aur-repo
          
          cp dist/PKGBUILD aur-repo/
          cp dist/.SRCINFO aur-repo/
          
          cd aur-repo
          git add PKGBUILD .SRCINFO
          
          if git diff --staged --quiet; then
            echo "No changes to AUR files."
          else
            git commit -m "Update to ${{ github.ref_name }}"
            git push
            echo "🚀 Successfully pushed to AUR!"
          fi