name: Test and Rolling Release

on:
  push:
    branches:
      - "master" # The rolling release will happen here
      - "**" # Tests will still run on all branches
    tags-ignore:
      - "**"
  pull_request:

jobs:
  # --- JOB 1: TESTS (Runs on all branches) ---
  test:
    runs-on: self-hosted-arch
    container:
      image: local/arch-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        run: cargo test --all-features --verbose

      - name: Run linter (clippy)
        run: cargo clippy --all-features -- -D warnings

  # --- JOB 2: ROLLING ANDROID BUILD (Only runs on 'master' and only if 'test' passes) ---
  rolling-android:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: self-hosted-ubuntu
    container:
      image: local/ubuntu-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry
        - gradle-cache:/root/.gradle
      env:
        RUSTFLAGS: "--remap-path-prefix ${{ github.workspace }}=/c --remap-path-prefix /usr/local/cargo=/cargo -C link-arg=-Wl,--build-id=none"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Keystore
        run: echo "${{ secrets.ANDROID_SIGNING_KEYSTORE_B64 }}" | base64 --decode > cfait-rolling.keystore

      - name: Build Rust JNI Libs
        run: |
          cargo ndk \
            -t aarch64-linux-android \
            -t armv7-linux-androideabi \
            -t x86_64-linux-android \
            -o ./android/app/src/main/jniLibs \
            --platform 28 \
            build --release --lib --features mobile

      - name: Build Signed Android APK
        env:
          KEYSTORE_FILE: "${{ github.workspace }}/cfait-rolling.keystore"
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Update Rolling Release on Codeberg
        env:
          TEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          # 1. Login
          tea login add --name codeberg --url ${{ github.server_url }} --token ${{ secrets.RELEASE_TOKEN }}

          TAG_NAME="rolling"
          REPO="${{ github.repository }}"

          # 2. Find and stage the APK
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "❌ Error: APK file not found!"
            exit 1
          fi

          # Clean staging folder
          mkdir -p rolling-dist
          cp "$APK_PATH" "rolling-dist/cfait-android-rolling.apk"

          # 3. Delete the old release (using your release.yml syntax)
          echo "Cleaning up old release..."
          tea release delete --repo "$REPO" --confirm "$TAG_NAME" || true

          # Pause to let the server database purge the record
          sleep 5

          # 4. Update the tag
          echo "Updating git tag..."
          git push origin :refs/tags/"$TAG_NAME" || true
          git tag -d "$TAG_NAME" || true
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

          # Pause to let the server index the new tag
          sleep 5

          # 5. Create the release using ONLY flags (fixes 'title is empty')
          echo "Creating new release..."
          tea release create \
            --repo "$REPO" \
            --tag "$TAG_NAME" \
            --title "Rolling Development Build" \
            --note "Automated signed build from commit ${{ github.sha }}" \
            --prerelease

          # 6. Upload the APK using your release.yml syntax
          echo "Uploading APK..."
          cd rolling-dist
          tea release assets create --repo "$REPO" "$TAG_NAME" "cfait-android-rolling.apk"
          cd ..

          # 7. Detailed Verification
          echo "--- VERIFICATION ---"
          tea release view --repo "$REPO" "$TAG_NAME"
          echo "--- END VERIFICATION ---"

          echo "✅ Rolling release process complete."
