name: Test and Lint

on:
  push:
    branches:
      - "**" # Run on all branches
    tags-ignore:
      - "**" # Do NOT run on tags
  pull_request:

jobs:
  test:
    runs-on: self-hosted-arch

    container:
      image: local/arch-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        run: cargo test --all-features --verbose

      - name: Run linter (clippy)
        run: cargo clippy --all-features -- -D warnings
