name: Feature Request
about: Suggest an idea to improve this project.
title: "FR: " 
labels: [enhancement]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (optional)
      description: Add any other context or mockups about the feature request here.
